project:
  type: book
  output-dir: docs
  execute-dir: project
  pre-render: setup-modules.r
  render:
    - "*.qmd"

book:
  title: "Box: Placing module system into R"
  subtitle: "Definitive Guide"
  author:
    - name: "Joshua Marie"
    - name: "John Riz Bagnol"
  # optional: author, date, subtitle, image, etc.
  sidebar:
    style: floating
    search: true
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "1 Introduction"
      chapters:
        - text: "1.1 Introduction"
          href: Chapter 1/1-intro.qmd
        - text: "1.2 Getting Started"
          href: Chapter 1/2-get-started.qmd
    - part: "2 Fundamentals of import system in {box} package"
      chapters:
        - text: "2.1 {box} Fundamentals"
          href: Chapter 2/1-box-fundamentals.qmd
        - text: "2.2 Array of imports and monikers"
          href: Chapter 2/2-imports.qmd
        - text: "2.3 Reloading modules"
          href: Chapter 2/3-reloading-modules.qmd
    - part: "3 Employment of Modules: Structures and constructions"
      chapters:
        - Chapter 3/1-struct-module.qmd
        - Chapter 3/2-struct-module-1.qmd
        - Chapter 3/3-struct-module-2.qmd
        - Chapter 3/4-add-data.qmd
        - Chapter 3/5-nested-modules.qmd
        # - Chapter 3/3.5-compiled-codes.qmd
    - part: "4 Testing Modules"
      chapters:
        - Chapter 4/1-testing-modules.qmd
        - Chapter 4/2-testthat-1.qmd
        - Chapter 4/3-testthat-2.qmd

  repo-url: https://github.com/joshuamarie/modules-in-r
  repo-actions: [edit, issue]

site-url: https://modules-in-r.joshuamarie.com

format:
  html:
    theme:
      light: [cosmo, custom-light.scss]
      dark: [darkly, custom-dark.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    code-copy: true
    code-overflow: wrap
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    bread-crumbs: false  

execute:
  warning: false
  message: false
  echo: true
  # freeze: auto
  