name: Publish Book Release
on:
  push:
    tags:
      - 'ed.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            knitr
            rmarkdown
            tidyverse
            testthat
            downlit
            xml2
            jsonlite
            yaml
            pak
          cache-version: 1

      - name: Install forked box package
        run: |
          Rscript -e 'pak::pak("joshuamarie/box@feature/carrier-module-support")'

      - name: Install TinyTeX
        run: quarto install tinytex

      - name: Render book to PDF
        run: quarto render --to pdf

      - name: Create release with auto-generated notes and PDF
        uses: softprops/action-gh-release@v2
        with:
          files: docs/*.pdf
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
