name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            testthat
            pak
          cache-version: 1
        
      - name: Install forked box package
        run: |
          Rscript -e 'pak::pak("joshuamarie/box@feature/carrier-module-support")'
      
      - name: Test module
        run: Rscript -e 'box::use(module/`__tests__`)'
      
      - name: Test `module/statistics/models` submodule
        run: Rscript -e 'box::use(module/statistics/models/`__tests__`)'
        
        